using UnityEngine;
using UnityEngine.SceneManagement; 
public class ButtonScript : MonoBehaviour
{
    [SerializeField] private string resetGameLevel = "Level1";
    public void ResetButton()
    {
        SceneManager.LoadScene(resetGameLevel);
    }
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    public void LoadScene( string name )
    {
        SceneManager.LoadScene(name);
        FindAnyObjectByType<AudioManager>().Play("PlayerLoad");
    }

}
